# Generated by Django 4.2.15 on 2024-09-16 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_address_building_no'),
        ('Ecom_app', '0002_auto_20240903_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='authentication.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='amount_due',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=128),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(editable=False, max_length=128, unique=True),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
